const menudata = [
  {
    id: 1,
    title: 'Rose Garden',
    category: 'Signature',
    price: '$5.50',
    img: '../BubbleTeaImg/RoseGarden.jpg',
    type: 'hot, cold',
    desc: 'An Amoria Signature',
  },
  {
    id: 2,
    title: 'Strawberry Matcha',
    category: 'Signature',
    price: 5.50,
    img: '../BubbleTeaImg/Strawberry MatchaLatte 1.jpg',
    desc: 'An Amoria Signature',
  },
  {
    id: 3,
    title: 'StrawBerry Slush',
    category: 'Signature',
    price: 5.50,
    img: '../BubbleTeaImg/StrawberrySlush3.jpg',
    desc: 'An Amoria Signature',
  },
  {
    id: 4,
    title: 'Ube Latte',
    category: 'Signature',
    price: 5.50,
    img: '../BubbleTeaImg/UbeLatte1.jpg',
    desc: 'An Amoria Signature',
  },
  {
    id: 5,
    title: 'HouseBlackTea',
    category: 'Teas',
    price: 6.00,
    img: '../Components/Categories/BubbleTeaImg/HouseBlackTea1.jpg',
    desc: `Tea based speciality`,
  },
  {
    id: 6,
    title: 'HouseMilkTea',
    category: 'Milk',
    price: 6.00,
    img: '../Components/Categories/BubbleTeaImg/HouseMilkTea1.jpg',
    desc: `Milk based speciality`,
  },
  {
    id: 7,
    title: 'French Daisy',
    category: 'Others',
    price: 6.00,
    img: '../Components/Categories/BubbleTeaImg/FrenchDaisy1.jpg',
    desc: `A Lorem Ipsum Type Drink`,
  },
  {
    id: 8,
    title: 'French Daisy',
    category: 'Others',
    price: 6.50,
    img: '../Components/Categories/BubbleTeaImg/FrenchDaisy1.jpg',
    desc: `A Lorem Ipsum Type Drink Mike Liu is Here`,
  },
];
export default menudata;